name: otp_plus
description: 'powerful, customizable package for handling PIN code. otp_plus makes it easy to implement elegant and responsive code input UIs.'
version: 1.0.8
homepage: https://github.com/fateme-shm/otp_plus
repository: https://github.com/fateme-shm/otp_plus
issue_tracker: https://github.com/fateme-shm/otp_plus/issues

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
